apiVersion: apps/v1
kind: Deployment
metadata:
  name: saqwu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saqwu
  template:
    metadata:
      labels:
        app: saqwu
    spec:
      containers:
      - image: okteto.dev/saqwu:latest
        name: saqwu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/saqwu/main/S-html.zip"
        - name: Vless_UUID
          value: "e0bc7a09-9c10-4f21-92bd-4c206f59b4c8"
        - name: Vless_Path
          value: "/vl6434"
        - name: Vmess_UUID
          value: "e0bc7a09-9c10-4f21-92bd-4c206f59b4c8"
        - name: Vmess_Path
          value: "/vm921343"
        - name: Share_Path
          value: "/v2link"
